# Autogenerated wrapper script for Bzip2_jll for x86_64-linux-gnu
export libbzip2

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libbzip2`
const libbzip2_splitpath = ["lib", "libbz2.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libbzip2_path = ""

# libbzip2-specific global declaration
# This will be filled out by __init__()
libbzip2_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libbzip2 = "libbz2.so.1.0"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"Bzip2")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list

    global libbzip2_path, libbzip2_handle
    libbzip2_path, libbzip2_handle = get_lib_path_handle!(LIBPATH_list, artifact_dir, libbzip2_splitpath)

    global PATH, LIBPATH
    PATH, LIBPATH = cleanup_path_libpath!(PATH_list, LIBPATH_list, ':')
    
end  # __init__()
